version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo4
      - MYSQL_USER=angga
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - app-network

  app:
    container_name: app
    build: .
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - 3030:3030
    expose:
      - 3030
    stdin_open: true
    environment:
      PORT: 3030
      HOST: 0.0.0.0
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql
      MYSQL_USER: angga
      MYSQL_PASSWORD: password
      MYSQL_DBNAME: todo4
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
